//! A [Riemann](http://riemann.io/) client library and command line interface.

pub mod client;
/// Layer one: Protobuf implementation generated by `protoc --rust_out`.
pub mod proto;
pub mod transport;

pub use self::client::Client;
pub use self::utils::{Error, Result};

/// Error and From implementations
mod utils {
    use std::ffi::OsString;
    use std::fmt::{Display, Formatter};
    use std::io::Error as IoError;

    use ::protobuf::Error as ProtobufError;

    use super::proto::Query;

    impl<'a> From<&'a str> for Query {
        fn from(query_str: &'a str) -> Self {
            Query::from(query_str.to_string())
        }
    }

    impl From<String> for Query {
        fn from(string: String) -> Self {
            let mut query = Query::new();
            query.set_string(string);
            query
        }
    }

    #[derive(Debug)]
    pub enum Error {
        Io(::std::io::Error),
        Protobuf(ProtobufError),
        Riemann(String),
        CACert(String),
        Key(String),
        PemParse(rustls::pki_types::pem::Error),
        TLS(rustls::Error),
        InvalidDNSNameError(rustls::pki_types::InvalidDnsNameError),
        InvalidHostname(OsString),
    }

    impl Display for Error {
        fn fmt(&self, f: &mut Formatter) -> ::std::fmt::Result {
            write!(f, "{:?}", self)
        }
    }

    impl From<IoError> for Error {
        fn from(err: IoError) -> Self {
            Error::Io(err)
        }
    }

    impl From<ProtobufError> for Error {
        fn from(err: ProtobufError) -> Self {
            Error::Protobuf(err)
        }
    }

    impl From<rustls::pki_types::pem::Error> for Error {
        fn from(err: rustls::pki_types::pem::Error) -> Self {
            Error::PemParse(err)
        }
    }

    impl From<rustls::Error> for Error {
        fn from(err: rustls::Error) -> Self {
            Error::TLS(err)
        }
    }

    impl From<rustls::pki_types::InvalidDnsNameError> for Error {
        fn from(err: rustls::pki_types::InvalidDnsNameError) -> Self {
            Error::InvalidDNSNameError(err)
        }
    }

    impl From<OsString> for Error {
        fn from(err: OsString) -> Self {
            Error::InvalidHostname(err)
        }
    }

    /// Result alias for Riemann client errors
    pub type Result<T> = ::std::result::Result<T, Error>;
}
